apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Welcome ðŸ‘‹</title>
        <style>
            body {
                background: #f8e8ff;
                font-family: Arial, sans-serif;
                text-align: center;
                padding-top: 100px;
            }
            h1 {
                color: #7b2cbf;
                font-size: 48px;
            }
            p {
                color: #6a4c93;
                font-size: 20px;
            }
            .box {
                background: white;
                padding: 20px;
                border-radius: 12px;
                display: inline-block;
                box-shadow: 0 0 15px rgba(0,0,0,0.1);
            }
        </style>
    </head>
    <body>
        <div class="box">
            <h1>Hello Suhani! ðŸ’œ</h1>
            <p>Your NGINX static site is deployed successfully.</p>
            <p>Powered by Argo CD ðŸš€</p>
        </div>
    </body>
    </html>
